import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/layout/LegalPage";

export const metadata: Metadata = {
  title: "Terms & Conditions | Eva",
  description: "Terms for using Eva AI companions and monthly subscriptions.",
  alternates: { canonical: "https://merigf.com/terms" }
};

export default function TermsPage() {
  return <LegalPage title="Terms & Conditions" summary="These terms apply to the Eva app and the MeriGF website. By creating an account or using Eva, you agree to these terms.">
    <section><h2>1. Who can use Eva</h2><p>You must be at least 18 years old and legally able to enter into this agreement. Provide accurate account information, keep your sign-in credentials private and do not share your account with others. You are responsible for activity you authorize on your account.</p></section>
    <section><h2>2. Conversations with AI</h2><p>Eva companions are artificial intelligence, not real people. Responses can be inaccurate, inconsistent or unavailable. They are not medical, mental-health, legal, financial or other professional advice. Do not rely on Eva for emergencies or important decisions; contact an appropriate professional or local emergency service instead.</p></section>
    <section><h2>3. Responsible use</h2><p>Do not use Eva for unlawful activity, exploitation, harassment, impersonation, or content involving sexual exploitation of minors. Do not attempt to bypass payment or security controls, disrupt the service, access another person's account or misuse personal information. We may restrict accounts that violate these terms, subject to applicable law.</p></section>
    <section><h2>4. Your content and memory</h2><p>You retain your rights in content you submit. You permit us to process that content to provide conversations, personalization and account features. Conversation history, profile information and saved memories may be used across companions on your account. Relevant data may be processed by service providers that support these features. Avoid sharing information you do not want processed, and do not submit another person's private information without permission.</p><p>This section is not a substitute for a separate privacy notice and does not waive your data-protection rights.</p></section>
    <section><h2>5. Subscriptions and payment</h2><p>The website's monthly Premium plan is INR 499 per month. The price, currency, taxes, billing period and available benefits shown at checkout govern your purchase. Google Play pricing may vary by location. Subscriptions renew automatically until cancelled, according to the payment provider's terms. Buying a subscription does not purchase ownership of the service or guarantee uninterrupted access.</p><p>Payments and subscription status are verified by our backend with the payment provider. An incomplete or pending payment may not activate Premium until verification completes. Use the same Eva account to access your verified membership on supported devices.</p></section>
    <section><h2>6. Cancellation and refunds</h2><p>You may cancel future renewals through the provider used for purchase. Cancellation normally leaves access available until the end of the paid billing period. Uninstalling the app, signing out or deleting an account does not itself cancel a subscription.</p><p>We do not provide discretionary refunds for change of mind, unused time or cancellation during a paid period. Read our <Link href="/refund-policy">Cancellation &amp; Refund Policy</Link> before purchasing. Mandatory consumer rights and payment-provider refund requirements remain unaffected.</p></section>
    <section><h2>7. Availability and changes</h2><p>Features, companions and availability may change, and maintenance or third-party outages may interrupt access. We will communicate material subscription changes as required by law and the relevant payment provider. Updated terms will be published here with an effective date; any consent or notice required by law will still be obtained or provided.</p></section>
    <section><h2>8. Rights and limitations</h2><p>Eva branding, application code and service assets remain the property of their respective owners. Use of the service does not transfer those rights. To the extent permitted by law, we do not guarantee the accuracy of AI responses or suitability for a particular purpose. Nothing in these terms excludes liability or remedies that cannot lawfully be excluded, or limits rights under applicable consumer law.</p></section>
  </LegalPage>;
}
